version: '3.4'

services:
  db:
      image: postgres
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      #volumes:
      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=0210
        - POSTGRES_DB=my_project
  dj:
    container_name: dj
    build: ./backend/my_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/my_project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  an:
    image: an
    build:
      context: ./my_project_front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 42001:4200
    depends_on:
      - dj
